### ISSUE TITLE
Terminal Color Palette

### ISSUE THREAD

**Issue by MinhTran0911** [AntonRyadovoy/pwsh_profile#1]
Hi, I really like the theme. May I also know your terminal color pallete? I'm trying with the official Nord color palette but everything looks so pale.

**Comment by AntonRyadovoy** [comment]
i reply u on reddit but if u still have problem, show me screenshot

**Comment by MinhTran0911** [comment]
Hi, I got this weird extra newline, when I have a prompt block with `"alignment": "right"`. Do you know how to fix this, or is it an oh-my-posh issue?
![image](https://github.com/user-attachments/assets/dd51c794-0236-434c-9565-99de2ee8bbc5)

**Comment by AntonRyadovoy** [comment]
I think u have an extra newline, lemme check ur code, give me link to it repo or paste it here
